apiVersion: v1
kind: Secret
metadata:
  name: aws-s3-secret
type: Opaque
data:
  aws-region: <base64-encoded-aws-region> 
  s3-bucket: <base64-encoded-s3-bucket>
  aws-access-key-id: <base64-encoded-aws-access-key-id>
  aws-secret-access-key: <base64-encoded-aws-secret-access-key>