apiVersion: v1
kind: Secret
metadata:
  name: aws-s3-secret
  namespace: commitly
type: Opaque
data:
  aws-region: dXMtZWFzdC0x
  s3-bucket: eW91ci1idWNrZXQtbmFtZQ==
  aws-access-key-id: eW91ci1hY2Nlc3Mta2V5
  aws-secret-access-key: eW91ci1zZWNyZXQta2V5