apiVersion: apps/v1
kind: Deployment
metadata:
  name: commitly-backend
  labels:
    app: commitly
    component: backend
spec:
  replicas: 2 # Start with 2 replicas for high availability
  selector:
    matchLabels:
      app: commitly
      component: backend
  template:
    metadata:
      labels:
        app: commitly
        component: backend
    spec:
      containers:
      - name: backend
        image: your-docker-repo/commitly-backend:latest # Relevant image here
        ports:
        - containerPort: 3000
        env:
        - name: MONGO_URI
          valueFrom:
            secretKeyRef:
              name: mongo-secret
              key: mongo-uri
        - name: JWT_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: jwt-secret
              key: jwt-secret-key
        - name: AWS_REGION
          valueFrom:
            secretKeyRef:
              name: aws-s3-secret
              key: aws-region
        - name: S3_BUCKET
          valueFrom:
            secretKeyRef:
              name: aws-s3-secret
              key: s3-bucket
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: aws-s3-secret
              key: aws-access-key-id
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: aws-s3-secret
              key: aws-secret-access-key
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
        livenessProbe:
          httpGet:
            path: /health # Your health check endpoint
            port: 3000
          initialDelaySeconds: 15
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 10