apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: commitly-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: commitly.your-domain.com # Replace with your domain
    http:
      paths:
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: commitly-backend-service
            port:
              number: 3000
      - path: /
        pathType: Prefix
        backend:
          service:
            name: commitly-frontend-service
            port:
              number: 80